### ISSUE TITLE
機能要望: アセットにハッシュを付加したい

### ISSUE THREAD

**Issue by tobigumo** [qrac/minista#119]
納品向けの綺麗なHTML出力というコンセプトから外れる要望ですみません

自分が管理するサイトを更新していく用途において、
アセット名にハッシュが付加されていればキャッシュの問題に悩むことがないため非常に便利です。
オプションでOn/Offの設定ができるようになるととても嬉しいです。

**Comment by qrac** [comment]
@tobigumo 
機能要望ありがとうございます！確かに便利そうですね。

ただ、色々試してみましたが短時間では実現できませんでした。

現状だと、コンフィグを以下のように書けばハッシュの付いたアセットを出力できますが、

```ts
{
  assets: {
    outName: "[name]-[hash]",
  },
}
```

ハッシュ値がHTMLに反映されず、以下のようなHTMLが出力されます。

```html
<link rel="stylesheet" href="/assets/index-[hash].css">
<script src="/assets/index-[hash].js"></script>
```

これはHTMLとアセットを別々に処理しているからです。

ハッシュの反映は時間がかかりそうでしたので、ひとまず現状だけ共有させていただきました！

**Comment by tobigumo** [comment]
ご検討ありがとうございます！
issueとしては閉じさせていただいて、気長に待ってます
