### ISSUE TITLE
Image、Pictureコンポーネント使用時のビルドを、一部キャッシュ化して高速化させたい

### ISSUE THREAD

**Issue by FuCrowRabbit** [qrac/minista#122]
Image、Pictureコンポーネントは非常に便利ですが、
ビルド時に毎回画像変換を行う都合上、使えば使うほどビルド時間がネックになってきています。

そこで一度画像を変換した事があるものについては、キャッシュのような機能を設けて画像変換をスキップさせたいです。

具体的には、以下の通りです。
1. 画像変換（ビルド）後に何らかの方法で、（変換）元画像のパスとハッシュ値のデータを保存するようにする。
2. ビルド時に保存されたデータを読み取り、以下の条件全てがtrueだった場合、その画像の変換をスキップする。
    - 変換したい画像パスと、保存されたデータに全く同じ元画像のパスが存在している
    - さらに、元画像に変更が加わっているかハッシュ値で照合する
    - 出力先に画像が存在している（ファイル名で確認）

非常に便利なツールなので、もっと盛り上げたいと思いました。
よろしくお願いいたします。

**Comment by FuCrowRabbit** [comment]
適当に作って実験してみました。
__minista_cache/cache.jsonを生成して、画像とオプションをハッシュ値として保存するようにしました。

https://github.com/FuCrowRabbit/minista-issue122/commit/390e4136a9aa4326650d3a89d4a53858937b3e35

===結果===
画像1,254枚を含めた`npm run build`

変更前：4分32秒
変更後：4分30秒（初回）、9秒（2回目以降）

**Comment by qrac** [comment]
@FuCrowRabbit 
ご協力ありがとうございます！！キャッシュを作る案は良いですね！

ちなみに、急いで導入した方が良いですか？
今すぐでなくてもよければ、現在開発中の[v4](https://github.com/qrac/minista/issues/121)に反映します。

**Comment by FuCrowRabbit** [comment]
@qrac 
ご確認のほど、ありがとうございます！

こちらの事情的には、早く欲しいところではありますが、
個人的な事情をOSSに反映するのは良くないと思いますし、
フォークして修正したコードがそのまま真マージされるわけでは無く、諸々修正・調整が入ると思いますので、
v4のリリース時で、問題ございません。

こちらはnpmの向き先を、v4リリースまでフォークした物に一時的に変えるなどで対応いたします。

ちなみに、v4のリリース時期は大まかに決まっていたりしますでしょうか？

**Comment by qrac** [comment]
@FuCrowRabbit 
ありがとうございます。v4はお盆休みあたりに完成させられたらなと考えています！

**Comment by qrac** [comment]
@FuCrowRabbit 
こちらをv4のデフォルト機能として実装しました！

- デフォルトでキャッシュの利用はオンになります
- キャッシュは画像Bufferのハッシュと生成条件のハッシュの2つを見ます
- キャッシュは開発モードと本番ビルドで共有できます
- キャッシュの置き場は `node_modules/.minista/image` 内です
- `node_modules` 内がクリアされるCIサービスの場合は明示して保持する必要があります
- Sample: https://github.com/qrac/minista/tree/v4/playground/image

**Comment by FuCrowRabbit** [comment]
@qrac ありがとうございます。
v4のリリースを心待ちにしております！

**Comment by FuCrowRabbit** [comment]
4.0.6で修正確認しました！
