### ISSUE TITLE
imgタグに書いたsrcのパスも、build時に出力してほしい

### ISSUE THREAD

**Issue by FuCrowRabbit** [qrac/minista#124]
# imgタグに書いたsrcのパスも、build時に出力してほしい

imgタグのsrc属性に`/src/**`でファイルを参照した場合、
`npm run dev`時は参照され、`npm run build`時にtransformされず結果的にリンク切れになります。

## TSX

```tsx
<img src="/src/assets/icons/icon.svg" />
```

## ビルド時（現状）

`/src/assets/icons/icon.svg`はBUILDされない。

```html
<img src="/src/assets/icons/icon.svg" /> <!-- リンク切れ -->
```

## ビルド時（期待される動き）

`/src/assets/icons/icon.svg`がBUILDされ、`/dist/assets/images/icon.svg`として出力される。

```html
<img src="/assets/images/icon.svg" /> <!-- 表示される -->
```

※ CSSの場合、`url("/src/assets/icons/icon.svg")`と書くとBUILDされます。統一性が欲しいところです。

**Comment by qrac** [comment]
@FuCrowRabbit 
ご指摘ありがとうございます！

以前はその仕様もあったのですが...画像パスがビルドされるか否かが分かりづらく、ビルドの度に画像パスのチェック処理が必要な点が画像コンポーネントと被るので削除しています。

v3の仕様だと以下のようにimportした画像はビルドされるのでパスも変換されます。

```tsx
import imageUrl from "../assets/image.svg"

export default function () {
  return (
    <img src={imageUrl} width="220" height="108" alt="" />
  )
}
```

もしくは、処理されない `public` に置いてパスの変換をしない。

```sh
public
┗ assets
      ┗ image.svg
```

```tsx
export default function () {
  return (
    <img src="/assets/image.svg" width="220" height="108" alt="" />
  )
}
```

ministaのv4はプラグイン制になりますので、オンオフ可能な機能として画像処理プラグインに含ませるか、または別のプラグインとして作るのはありかと思います。

```
pluginImage({ autoImport: true })
```

```
pluginImageAutoImport()
```

**Comment by FuCrowRabbit** [comment]
ご対応ありがとうございました。
取り急ぎ、v4で確認したいと思います。

**Comment by FuCrowRabbit** [comment]
4.0.6で修正確認しました！
