### ISSUE TITLE
動的なパスを重ねると正常に動作・書き出しが出来ない

### ISSUE THREAD

**Issue by hrgwtr** [qrac/minista#129]
興味深いライブラリだと思い案件で使用したいと思っています。
ドキュメントを確認しながら進めていますが、ドキュメントの相違点で１つ明確なのは`pnpm`を使用しています。
`getStaticData`を使用した動的なデータの取得と表示については動作確認出来ています。

---

## 期待値：
`/:lang/post/:id.tsx`という動的パスを重ねたページパスを使用したいのですが、思ったように動作しません。

## 実行したこと：
`/pages/[lang]/post/[id].tsx`の形でファイルを作成しました。`dev`コマンドで確認した際には`no match`となります。
`/pages/[lang]/index.tsx`は期待通り表示されました。
試しに`build`してみたところ、`[lang] -> lang]`に`[id].tsx -> id].html`として書き出されていました。
```
例：
dist/:lang]/post/id].html
dist/lang/index.html
```
## 試してみたこと：
動的な部分の命名規則を`/pages/:lang/post/:id.tsx`で作成したところ、`dev`コマンドでは **期待通りの動作** をしました。
`build`コマンドでは`:lang`の動的な解釈がされず、`:id.tsx`は期待通りのhtmlが生成されていました。
```
例：
dist/:lang/post/1234.html
```

## 質問：
動的なパスを重ねて使用したいと思っています。
手元で試してみたのですが解決しなかったので質問させて頂きました。
なにか見落としがあるかもしれませんが、ご確認いただければと思います。

---
使用ライブラリ：
```
    "@types/react": "^18.2.16",
    "@types/react-dom": "^18.2.7",
    "minista": "^3.1.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "^5.1.6"
```

**Comment by qrac** [comment]
@hrgwtr 
ご報告ありがとうございます！
複数の動的パスの変換には対応していませんでしたので、v3.1.7にて対応しリリースしました！よろしくお願いします。

- https://github.com/qrac/minista/releases/tag/3.1.7

**Comment by hrgwtr** [comment]
@qrac 
getStaticDataで`paths`にlangを指定し`dev, build`とも動作確認出来ました。
ありがとうございました！
