### ISSUE TITLE
Windowsで動作しません

### ISSUE THREAD

**Issue by syon** [qrac/minista#37]
こんにちは。minista のソリューションに興味を持ちまして、手元の環境で試しております。
しかし `npm run dev` でエラーが発生し、先に進めず困っています。

ドキュメントやサイトをざっくり拝見しましたが、OS制限の記載は見つけられませんでした。
Windowsはサポート外なのでしょうか？
環境依存のお話でしたらできる限り情報をお出ししますので、ご確認いただけますと幸いです。

以下、インストールからエラーまでの軌跡です。

<img width="674" alt="error" src="https://user-images.githubusercontent.com/3148102/166408049-c91ec6a8-84e8-4415-90ac-a7e0901ce245.png">

<img width="674" alt="error2" src="https://user-images.githubusercontent.com/3148102/166408331-b532f888-3c49-47d5-9801-d6c404e4ea5c.png">

**Comment by qrac** [comment]
ご報告ありがとうございます！
Windowsを開発で使っていないので気づきませんでした。おそらくはパスを解決できていないバグなので、直せないか試してみます！

**Comment by qrac** [comment]
@syon
バージョン `2.3.2` にて修正完了しました！
`npm i -D minista@latest` でアップデートするか、`npm init minista@latest` で始めてみてください。検証環境は以下の通りです。

- OS: win 11, v21H2
- PowerShell: v7.2.3
- VS Code: v1.66.2
- Node.js: v16.15.0

**Comment by syon** [comment]
@qrac
問題なく動作することを確認しました！
素早いご対応ありがとうございました。
