### ISSUE TITLE
html langを指定できるようにする

### ISSUE THREAD

**Issue by sharapeco** [qrac/minista#56]
多言語サイトにおいて `<html lang="en">` のような出力をしたいのですが、現状だと src/render.tsx に `lang="ja"` がハードコーディングされているため

```jsx
  <Head>
    <html lang={lang} />
  </Head>
```

のように指定すると最終出力が

```html
<html lang="ja" lang="en">
```

のように、二重に属性が出力されてしまいます。

単純に src/render.tsx から指定を外せば目的の出力はできるのですが、過去との互換性を考えるとデフォルト値が設定されている方がいいと思います。

**Comment by qrac** [comment]
@sharapeco 
ご指摘ありがとうございます！v2.8.1にて修正しましたのでご確認ください。

**Comment by sharapeco** [comment]
早速ありがとうございます！ ばっちり動きました！

helmet.htmlAttributes を調べればよかったのですね。勉強になります。
