### ISSUE TITLE
base指定時、全文検索機能が生成するJSONのパスにbaseパスが反映されない

### ISSUE THREAD

**Issue by mktbsh** [qrac/minista#61]
## 環境

- OS: Mac OS Montrey(v12.4)
- Browser: Google Chrome
- Node.js: v18.7.0
- react/react-dom: v17.0.2
- minista: 2.8.2
- typescript: 4.7.4

## 期待値

全文検索結果に含まれるアイテムのパスに `base` オプションで指定したパスが含まれた状態で正常に画面遷移が行えること

## 実際の結果

`The server is configured with a public base URL of /xxx/ - did you mean to visit /xxx/page/ instead?` が表示される

## 再現手順

1. minista.config.ts で全文検索を有効にする
2. minista.config.ts で base オプションを設定する
3. 適当なページに Search コンポーネントを配置し、検索を行う
4. 検索結果をクリックする

## 再現するサンプルプロジェクト

https://github.com/mktbsh/minista-bugreport-sample

## その他・備考

[buildSearchJson](https://github.com/qrac/minista/blob/4f0e82e7c727dedaf47f675a2818bbae1674f6e0/src/build.tsx#L1051)を修正すれば問題なさそうというところまで調査しました。
手が空いたらプルリクを作成しようと思っていますが、先に対応できる方がいたら対応していただけると助かります。

**Comment by qrac** [comment]
@mktbsh 
ご報告ありがとうございます！！修正したv2.8.3をリリースしました。
ministaをアップデートして、Searchコンポーネントのパスにbaseを加えていただくと正常に動くかと思います。

```bash
$ npm i -D minista@latest 
```

```tsx
// src/components/block-search.tsx
import { Search } from "minista"

export default () => {
  return (
    <Search
      jsonPath="/test/assets/search.json"
      placeholder="Search..."
      className="block-search"
      searchFieldClassName="block-search-field"
      searchListClassName="block-search-list"
    />
  )
}
```

**Comment by mktbsh** [comment]
@qrac 
迅速な対応ありがとうございます。

サンプルプロジェクトで期待通りに動作することを確認しました。
こちらで修正してプルリクエストを出せばよかったところを対応していただきありがとうございました。
